### ISSUE TITLE
Grammar error on No code AI cheat sheet

### ISSUE THREAD

**Issue by BeckyBrekke** [MicrosoftDocs/ai-builder#104]
Small grammar error on the text on the pdf called No code AI cheat sheet. 
[No code AI cheat sheet](https://aka.ms/aibuildercheatsheet)
Under Build Generative AI Capabilities and then Summarize text it should read: Generate summary for a give**n** text. The n is missing in given. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df883391-2bf6-2443-349d-4969356edb7f
* Version Independent ID: 11878c2a-ea19-e2f9-7d37-5a26325fd50a
* Content: [Overview of AI Builder](https://learn.microsoft.com/en-us/ai-builder/overview)
* Content Source: [ai-builder-docs/overview.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/overview.md)
* Service: **aibuilder**
* GitHub Login: @Phil-cmd
* Microsoft Alias: **plarrue**

**Comment by v-aangie** [comment]
@BeckyBrekke - Thanks for your feedback. We have updated the docs to fix the typo in the article and the download. The updated content will be live in a few minutes. Closing this issue.
