### ISSUE TITLE
Downloadable graphic has a typo

### ISSUE THREAD

**Issue by LindaCicero** [MicrosoftDocs/ai-builder#105]
There is a typo in the downloadable graphic (cheat sheet). One instance of "given" says "give" without the last letter. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: df883391-2bf6-2443-349d-4969356edb7f
* Version Independent ID: 11878c2a-ea19-e2f9-7d37-5a26325fd50a
* Content: [Overview of AI Builder](https://learn.microsoft.com/en-us/ai-builder/overview?source=docs)
* Content Source: [ai-builder-docs/overview.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/overview.md)
* Service: **aibuilder**
* GitHub Login: @Phil-cmd
* Microsoft Alias: **plarrue**

**Comment by v-aangie** [comment]
@LindaCicero - Thanks for your feedback. We have updated the docs to fix the typo in the article and the download. The updated content will be live in a few minutes. Closing this issue.

**Comment by LindaCicero** [comment]
Wow! That was fast! 😊
