### ISSUE TITLE
Automatic Prediction ind CDS and Predict in Automate doesn't work

### ISSUE THREAD

**Issue by philippschaefer4** [MicrosoftDocs/ai-builder#13]
Hi,
I managed to train a (binary) prediction model, publish it and click on "run now" to use it on my data. But the problem is that this last step doesn't do anything. The three new fields in my entity are left completely empty. As far as I understand "run now" should fill those fields. 
On the other hand I can also not use my Prediction models in Power Automate. I can see the trained model in the list, but when I select it I get the error: "Failed to get dynamic schema". Strangely all other kinds of AI Builder models work without problems here.

Does anybody have an idea what could be the problem? I didn't find the problem elsewhere on the internet. 

Thanks in advance,
Philipp

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 9f2808e5-e90b-d76e-e682-c3e07d3d9439
* Version Independent ID: 7c0a5631-fce9-6b2d-d7ba-f89b7ebb483b
* Content: [Train and publish your prediction model -  AI Builder](https://docs.microsoft.com/en-us/ai-builder/prediction-train-model#feedback)
* Content Source: [ai-builder-docs/prediction-train-model.md](https://github.com/MicrosoftDocs/ai-builder/blob/master/ai-builder-docs/prediction-train-model.md)
* Service: **powerapps**
* GitHub Login: @Dean-Haas
* Microsoft Alias: **sdarapu; mfotedar**

**Comment by philippschaefer4** [comment]
Hey again,
I solved at least half the "problem", which was my own ignorance. (Of course) the training records aren't evaluated, because there are already the correct answers for the target field. When I create a new record with the target field missing the prediction fields are filled correctly.
Nevertheless I still can't use the prediction model in Power Automate in the "current CDS environment"-Node (in contrast to all other AI Builder models like text classification). There is still this error: "Failed to get dynamic schema".
But since my main problem is solved, the thread may be closed.

**Comment by JoeFernandezMS** [comment]
Hi @philippschaefer4, indeed a prediction model cannot be used in Power Automate today. Even thought they are shown, they will not work in Power Automate.
