### ISSUE TITLE
Page title shows as Language detection 

### ISSUE THREAD

**Issue by gmsantos** [MicrosoftDocs/ai-builder#15]
In tab page title, it shows Language detection prebuilt AI model. I think that should be Text recognition prebuilt AI model.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c38c8c14-4bce-09c9-f711-511a49a9e6d3
* Version Independent ID: 02df0034-6281-2b7a-825a-313f55a35da5
* Content: [Language detection prebuilt AI model -  AI Builder](https://docs.microsoft.com/en-us/ai-builder/prebuilt-text-recognition#feedback)
* Content Source: [ai-builder-docs/prebuilt-text-recognition.md](https://github.com/MicrosoftDocs/ai-builder/blob/master/ai-builder-docs/prebuilt-text-recognition.md)
* Service: **powerapps**
* GitHub Login: @alanabrito
* Microsoft Alias: **alanab**

**Comment by Dean-Haas** [comment]
Thanks for logging this. There must have been a glitch, as this is showing "Text Recognition" for me.

**Comment by gmsantos** [comment]
Strange @Dean-Haas  ... I tried again, in another computer and with a private session, but title tab still different:

![image](https://user-images.githubusercontent.com/1991286/76338904-26b3d880-62d8-11ea-9606-39887c7c6773.png)

**Comment by Dean-Haas** [comment]
I see. this fix will publish at 5pm Redmond time. Thank you!
