### ISSUE TITLE
Create a new record screenshot doesn't match environment

### ISSUE THREAD

**Issue by pglevy** [MicrosoftDocs/ai-builder#16]
When I try to follow these instructions, the Create a new record action has fields for "Environment" and "Entity Name," not "Entity name, key phrase, and text." Phrases is not an option for Entity Name, so I cannot proceed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 35a7f3ce-bb6e-c7a9-01c2-b1ff155f59f2
* Version Independent ID: 9ad6a16a-023f-28d9-19bb-79cca972d77d
* Content: [Use the key phrase extraction prebuilt model in Power Automate - AI Builder](https://docs.microsoft.com/en-us/ai-builder/flow-key-phrase-extraction#feedback)
* Content Source: [ai-builder-docs/flow-key-phrase-extraction.md](https://github.com/MicrosoftDocs/ai-builder/blob/master/ai-builder-docs/flow-key-phrase-extraction.md)
* Service: **powerapps**
* GitHub Login: @alanabrito
* Microsoft Alias: **alanab**

**Comment by JoeFernandezMS** [comment]
Hi @pglevy, _Phrases_ is a example entity. You most probably wont have that entity on your environment but you can choose any other one that might fit your needs. You can also put a different action: like saving the extracted key phrases in an Excel file. 

To not see the "Environment" input you will need to use the **Common Data Service (current environment)** connector.
