### ISSUE TITLE
Predict from AI Builder is not an option

### ISSUE THREAD

**Issue by bobkill** [MicrosoftDocs/ai-builder#20]
In the documentation, we're told to search "Predict" and select either "Predict from AI Builder" or "Predict from Common Data Service."

I can't see either of those options.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a5e28295-0972-30de-b967-a7722acee32f
* Version Independent ID: 2ef61e8f-b900-64c9-354c-8d1d57dfad28
* Content: [Use Predict action in Power Automate -  AI Builder](https://docs.microsoft.com/en-us/ai-builder/predict-action-pwr-automate)
* Content Source: [ai-builder-docs/predict-action-pwr-automate.md](https://github.com/MicrosoftDocs/ai-builder/blob/master/ai-builder-docs/predict-action-pwr-automate.md)
* Service: **powerapps**
* GitHub Login: @antonio-rodrigues
* Microsoft Alias: **antrod**

**Comment by Dean-Haas** [comment]
Did you follow this step from the note at the top of the topic?
********
Important

To use AI Builder models in Power Automate, you have to create the flow inside a solution. The steps below won't work if you don't follow these instructions first: Create a flow in a solution.
**********

**Comment by bobkill** [comment]
I ended up getting it to show up, but I definitely can't explain how I eventually got there.

I appreciate the response.


Bob Kill | Data Scientist | Quantum Workplace
<mailto:wesley.laughlin@quantumworkplace.com><mailto:bob.kill@quantumworkplace.com>bob.kill@quantumworkplace.com<mailto:bob.kill@quantumworkplace.com> | Phone/Fax: 1.888.415.8302
quantumworkplace.com<https://urldefense.proofpoint.com/v2/url?u=http-3A__www.quantumworkplace.com_&d=DwMFAg&c=Cu5g146wZdoqVuKpTNsYHeFX_rg6kWhlkLF8Eft-wwo&r=FF2sfr9R4gLZaUxtXYrEEQDAPlQS4pX2LPkPmgB6xq0&m=oQDQ6j87mxMw_69Mh8mmxs-4GP3lgzgCwOZV4_NXXFg&s=R39qPuYI1vM3W2sllnOMXdmt80puhOmqgVGU8mW0awY&e=> | 13810 FNB Parkway, Suite 401, Omaha, NE 68154


________________________________
