### ISSUE TITLE
Table formatting messed up in prediction model performance

### ISSUE THREAD

**Issue by jarennert** [MicrosoftDocs/ai-builder#21]
![image](https://user-images.githubusercontent.com/53295938/85408870-1942f700-b533-11ea-9c28-0b4dfa0b399a.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: a2e2023e-178b-019e-b906-8320d5371d7e
* Version Independent ID: 32a7ce9f-9573-7808-7a9e-96496d46eeb9
* Content: [Prediction model performance - AI Builder](https://docs.microsoft.com/en-us/ai-builder/prediction-performance)
* Content Source: [ai-builder-docs/prediction-performance.md](https://github.com/MicrosoftDocs/ai-builder/blob/master/ai-builder-docs/prediction-performance.md)
* Service: **powerapps**
* GitHub Login: @Dean-Haas
* Microsoft Alias: **norliu**

**Comment by Dean-Haas** [comment]
fixed!
