### ISSUE TITLE
Multiple language suppport

### ISSUE THREAD

**Issue by HinaMS** [MicrosoftDocs/ai-builder#22]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18f467d3-3b0c-aec7-4129-1670b4df4acd
* Version Independent ID: f85a2bb8-ab47-24d8-c312-f1bd3bccabff
* Content: [Use the form processor component in Power Apps - AI Builder](https://docs.microsoft.com/en-us/ai-builder/form-processor-component-in-powerapps#feedback)
* Content Source: [ai-builder-docs/form-processor-component-in-powerapps.md](https://github.com/MicrosoftDocs/ai-builder/blob/master/ai-builder-docs/form-processor-component-in-powerapps.md)
* Service: **powerapps**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by HinaMS** [comment]
Form processor component in Power Apps only support English language at this time, because: "The Form Processor in AI Builder uses the Form Recognizer Cognitive Service under the hood, which only supports English at this time."  This we have received this information from DEV. Lets add this information on public facing document as well.

**Comment by JoeFernandezMS** [comment]
Submitted PR to state in the requirements that the only supported language currently for form processing is English: https://github.com/MicrosoftDocs/ai-builder-pr/pull/295
