### ISSUE TITLE
Common Data Service is not available in options

### ISSUE THREAD

**Issue by Yonet** [MicrosoftDocs/ai-builder#29]
Issues:
- Tutorial instruction option doesn't exists on the app. 
-  No information about the different data table options. 
- Tutorial suggests "Select the Common Data Service table and the column that contains your data." but doesn't mention how to upload your data to to the common data service or any other option from the table drop down.

Reproduce:

- Power app AI Builder: create new from Entity Extraction example app.
- When prompted to add data, clicked the [learn more link](https://docs.microsoft.com/ai-builder/entity-extraction-overview?WT.mc_id=aiml-13738-ayyonet), there was no data about how to choose any of the data table options.
- Navigated to the [extraction model tutorial](https://docs.microsoft.com/ai-builder/entity-extraction-create?WT.mc_id=aiml-13738-ayyonet#upload-examples-of-your-text-data) that suggest to choose the Common Data Service but the Service is not one of the options. See image below:
<img width="926" alt="Screenshot 2021-02-08 153151" src="https://user-images.githubusercontent.com/3523671/107294721-cca91f00-6a22-11eb-812a-a70f7e647906.png">

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d9b6daab-c308-202d-7d17-4ba259c14f9b
* Version Independent ID: 4edbd890-daac-f38d-f484-a11d3aade463
* Content: [Create a custom entity extraction AI model - AI Builder](https://docs.microsoft.com/en-us/ai-builder/entity-extraction-create?source=docs)
* Content Source: [ai-builder-docs/entity-extraction-create.md](https://github.com/MicrosoftDocs/ai-builder/blob/master/ai-builder-docs/entity-extraction-create.md)
* Service: **aibuilder**
* GitHub Login: @mfotedar
* Microsoft Alias: **mfotedar**

**Comment by v-aangie** [comment]
@Yonet — Thanks for your feedback. We have updated the docs to fix information about the https://docs.microsoft.com/en-us/ai-builder/entity-extraction-create?source=docs feature, and the updated content is live. Closing this issue.
