### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by janwillemkeizer** [MicrosoftDocs/ai-builder#30]
[Enter feedback here]
Binary prediction is when the question asked has two possible answers. For example: yes/no, **tru**/false, on-time/late, go/no-go, and so on.

Tru = True.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04327fe0-25b9-1eca-bd13-2dd377b27cf7
* Version Independent ID: 40c93dff-6b9c-3d51-599d-d99eb0ca59f1
* Content: [Overview of the prediction model - AI Builder](https://docs.microsoft.com/en-us/ai-builder/prediction-overview)
* Content Source: [ai-builder-docs/prediction-overview.md](https://github.com/MicrosoftDocs/ai-builder/blob/master/ai-builder-docs/prediction-overview.md)
* Service: **aibuilder**
* GitHub Login: @Dean-Haas
* Microsoft Alias: **norliu**

**Comment by v-aangie** [comment]
@janwillemkeizer — Thank you for the feedback. The typo has been corrected and the change will go live by end-of-day.
