### ISSUE TITLE
File doesn't work. I downloaded and installed the solution, but when I select healthcare_feedback it tells me there is no data.

### ISSUE THREAD

**Issue by joholmes123** [MicrosoftDocs/ai-builder#32]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: d0c05de5-02d3-f982-56ad-b60d9c97c7ca
* Version Independent ID: e2b455cf-5331-c5b4-a6f8-e4dac5d292da
* Content: [Use sample data to do category classification  - AI Builder](https://docs.microsoft.com/en-us/ai-builder/text-classification-sample-data)
* Content Source: [ai-builder-docs/text-classification-sample-data.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/text-classification-sample-data.md)
* Service: **aibuilder**
* GitHub Login: @amina196
* Microsoft Alias: **aminab**

**Comment by v-aangie** [comment]
Asked Raj Virk for current owner. It's no longer amina196.

**Comment by v-aangie** [comment]
@joholmes123 — Thanks for your feedback. We have updated the docs to fix information about the healthcare_feedback data, and the updated content will be live this evening. See https://docs.microsoft.com/en-us/ai-builder/text-classification-sample-data.

Closing this issue.
