### ISSUE TITLE
Sample link syntax incomplete

### ISSUE THREAD

**Issue by Pasark** [MicrosoftDocs/ai-builder#4]
The link to the sample is not entered correctly. A space between microsoft/ and PowerApps breaks the syntax. The url is correct when copy-pasted and fixed.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c45f567c-ca14-196e-3d85-800fd4eb1571
* Version Independent ID: a2d0b3b7-2213-e9e0-b3ea-2f4f0f92c14d
* Content: [Use sample data to do prediction  -  AI Builder](https://docs.microsoft.com/en-us/ai-builder/prediction-sample-data#feedback)
* Content Source: [ai-builder-docs/prediction-sample-data.md](https://github.com/MicrosoftDocs/ai-builder/blob/master/ai-builder-docs/prediction-sample-data.md)
* Service: **powerapps**
* GitHub Login: @amina196
* Microsoft Alias: **aminab**

**Comment by Dean-Haas** [comment]
This has been fixed. Thanks.
