### ISSUE TITLE
Spelling issue

### ISSUE THREAD

**Issue by vihars711** [MicrosoftDocs/ai-builder#44]
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3c6628-8673-e44d-9a17-553030b6b29d
* Version Independent ID: 679b1654-ffe3-5811-6985-9333195b34d0
* Content: [Use the form processing model in Power Automate - AI Builder](https://docs.microsoft.com/en-us/ai-builder/form-processing-model-in-flow)
* Content Source: [ai-builder-docs/form-processing-model-in-flow.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/form-processing-model-in-flow.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by v-aangie** [comment]
@vihars711 - Thank you for your feedback. I have updated https://docs.microsoft.com/en-us/ai-builder/form-processing-model-in-flow#filter-email-signature-from-a-flow-so-that-is-is-not-processed-by-the-form-processing-model-microsoft-365-outlook to correct the wording in the heading. It should be live in a few hours. Closing this issue. Thanks!
