### ISSUE TITLE
Description of some warnings missed

### ISSUE THREAD

**Issue by soutchilin** [MicrosoftDocs/ai-builder#45]
Hi,

The help tip points to this page in MS Docs. Therefore I address it here. I miss explanation of the following warnings, that are displayed after my model has been trained:
- Some columns were dropped during training.
- Some columns had low relevance.

Especially 
Can you please address these?

Cheers,
Alexander

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: fd3e64b9-73db-28a4-eb88-e5afd66376ca
* Version Independent ID: b1d3dc37-0c1f-cc4b-ecac-b9498d5de576
* Content: [Prediction model training errors and warnings - AI Builder](https://docs.microsoft.com/en-us/ai-builder/prediction-training-report)
* Content Source: [ai-builder-docs/prediction-training-report.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/prediction-training-report.md)
* Service: **aibuilder**
* GitHub Login: @norliu
* Microsoft Alias: **norliu**

**Comment by v-aangie** [comment]
@soutchilin - Thank you for your feedback. Can you please provide clarification? It looks like there's an explanation of the warning about a dropped column - https://docs.microsoft.com/en-us/ai-builder/prediction-training-report#warning-column-might-be-dropped-from-training-model. Did this not address your issue? However, I didn't see anything on low relevance. Please let me know what you would like answered specifically. Thanks!

**Comment by v-aangie** [comment]
@soutchilin - Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
