### ISSUE TITLE
Flow should now be called "Power Automate"

### ISSUE THREAD

**Issue by jarennert** [MicrosoftDocs/ai-builder#5]
Flow should now be called "Power Automate".

**Example: ai-builder-docs/use-model.md**
![image](https://user-images.githubusercontent.com/53295938/70050973-75aeeb00-15d0-11ea-9fdb-bf0356c6f9cd.png)

**Comment by Dean-Haas** [comment]
Thanks Josh.  I swept the repo for this change, but must have missed this occurrence. I’ll double check all the docs. We do still refer to “A Flow” within Power Automate, ie the product name changes, but we still refer to a flow as the thing you create using PA.

Dean Haas
Murphy & Associates
TECHNICAL WRITER | MICROSOFT CLOUD + AI | CLOUD DESIGN STUDIO
v-dehaas@microsoft.com<mailto:v-dehaas@microsoft.com> | 360-440-6333
