### ISSUE TITLE
Need to assign security role about AI Models to allow other users to edit models

### ISSUE THREAD

**Issue by tanimani** [MicrosoftDocs/ai-builder#50]
For editing shared AI Models, it need to assign security roles too.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b13dc4b6-2279-f5c9-8f22-449af62cc720
* Version Independent ID: 433e3811-0f71-8799-de61-56ab4e82231c
* Content: [AI モデルを共有する - AI Builder](https://docs.microsoft.com/ja-jp/ai-builder/share-model)
* Content Source: [ai-builder-docs/share-model.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/share-model.md)
* Service: **aibuilder**
* GitHub Login: @Antoine2F
* Microsoft Alias: **antode**

**Comment by v-aangie** [comment]
@Tanimani - Thanks for your feedback. We will soon look into this issue and update https://docs.microsoft.com/ja-jp/ai-builder/share-model.
