### ISSUE TITLE
Explanation not sufficient, missing steps

### ISSUE THREAD

**Issue by nadjaklein** [MicrosoftDocs/ai-builder#51]
Hi there,

I'm trying to create a canvas app where I can upload an image or take a photo and it's using my custom vision model to classify it.
I was pointed to the Power Fx documentation by a colleague, but I just wanted to give feedback, that it is not possible to implement it with the documentation. (I'm working as a CSA, so kind of stepping in the shoes of a customer here)

It's great that you put an animation in the end of exactly the use case that I am looking into, but instead of showing just the solution it would be great to see the steps necessary to implement it. This shouldn't be a marketing slide, but a documentation of how to properly use the functionality.
This is not useful for our customers!

Thanks,
Nadja

[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc82aee7-7245-42a3-41e9-a8d2aa3eed19
* Version Independent ID: cc82aee7-7245-42a3-41e9-a8d2aa3eed19
* Content: [Use image classification model by Lobe in Power Apps (preview) - AI Builder](https://docs.microsoft.com/en-us/ai-builder/image-classification-component-in-powerapps)
* Content Source: [ai-builder-docs/image-classification-component-in-powerapps.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/image-classification-component-in-powerapps.md)
* Service: **aibuilder**
* GitHub Login: @mbeissinger
* Microsoft Alias: **mabeis**

**Comment by v-aangie** [comment]
@nadjaklein - Thanks for your feedback. We will soon look into this issue regarding https://docs.microsoft.com/en-us/ai-builder/image-classification-component-in-powerapps.

**Comment by v-aangie** [comment]
@nadjaklein - Thanks for your feedback. This feature is planned to be updated in June. We will update the documentation at that time. Closing this issue.
