### ISSUE TITLE
Conflicting messaging

### ISSUE THREAD

**Issue by brendon-colburn** [MicrosoftDocs/ai-builder#53]
In docs we are still marking this as a Preview capability but on this blog post it's listed as GA: 

https://powerautomate.microsoft.com/en-us/blog/enhancing-ai-for-low-code-development-with-ai-builder/

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6f211a69-40c2-6205-2bfd-8829c1171fa0
* Version Independent ID: 21692957-7ef5-9f52-58b4-38de1412d598
* Content: [Bring your own model into AI Builder - AI Builder](https://docs.microsoft.com/en-us/ai-builder/byo-model)
* Content Source: [ai-builder-docs/byo-model.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/byo-model.md)
* Service: **aibuilder**
* GitHub Login: @Raj-Virk
* Microsoft Alias: **rajvirk**

**Comment by v-aangie** [comment]
@brendon-colburn - Thanks for your feedback. We'll correct this issue soon.

**Comment by v-aangie** [comment]
@brendon-colburn - Thanks for your feedback. We have updated the TOC to remove (preview) and the changes will go live in a few hours. Closing this issue.
