### ISSUE TITLE
Update action name from "New version" to "Edit model"

### ISSUE THREAD

**Issue by cimaja** [MicrosoftDocs/ai-builder#54]
**Current:**
To create a new version, select **New version** at the top of the page.

**Edit:**
To create a new version, select **Edit model** at the top of the page.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1dc86433-875e-b3c4-0d4d-f21e14a27158
* Version Independent ID: b55397ee-0c6b-b3b4-81ee-6573752b5bc3
* Content: [Manage your model in AI Builder - AI Builder](https://docs.microsoft.com/en-us/ai-builder/manage-model)
* Content Source: [ai-builder-docs/manage-model.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/manage-model.md)
* Service: **aibuilder**
* GitHub Login: @paulnog
* Microsoft Alias: **paulnog**

**Comment by v-aangie** [comment]
@cimaja - Thanks for your feedback. We have updated the docs to fix https://docs.microsoft.com/en-us/ai-builder/manage-model#create-a-new-version, and the updated content will be live today. Closing this issue.
