### ISSUE TITLE
Contradictory information on Sentiment Analysis

### ISSUE THREAD

**Issue by jaspreetjolly** [MicrosoftDocs/ai-builder#58]
[Just wanted to bring to your notice a discrepancy in [Overview of prebuilt AI models - AI Builder | Microsoft Docs] (https://docs.microsoft.com/en-us/ai-builder/prebuilt-overview). It states Sentiment Analysis is available in Power Automate only. However, when you go to [Sentiment analysis prebuilt AI model - AI Builder | Microsoft Docs] (https://docs.microsoft.com/en-us/ai-builder/prebuilt-sentiment-analysis) first topic is using it in PowerApps.]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 47dc3b02-39b8-0749-fe30-f455965ed3e1
* Version Independent ID: 39747c21-163c-29c5-f461-7d94140de5ad
* Content: [Overview of prebuilt AI models - AI Builder](https://docs.microsoft.com/en-us/ai-builder/prebuilt-overview)
* Content Source: [ai-builder-docs/prebuilt-overview.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/prebuilt-overview.md)
* Service: **aibuilder**
* GitHub Login: @v-aangie
* Microsoft Alias: **angieandrews**

**Comment by v-aangie** [comment]
@jaspreetjolly - Thanks for your feedback. We will soon fix this issue.

**Comment by v-aangie** [comment]
@jaspreetjolly - Thanks for your feedback. We've updated the docs to fix information about the issue in  [Overview of prebuilt AI models](https://docs.microsoft.com/en-us/ai-builder/prebuilt-overview), and the updated content is live. Closing this issue.
