### ISSUE TITLE
Format of AI Builder consumption report is not the latest

### ISSUE THREAD

**Issue by tanimani** [MicrosoftDocs/ai-builder#59]
The latest report format is below
- Date
- UserId
- EnvironmentId
- AIConsumption
- IsTrial

Current docs is below
- Date
- EnvironementId
- AI Consumption

Please update screen capture and add description about these columns.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: de5411d9-5293-2bf2-7c2c-e264456bbdfe
* Version Independent ID: bcac04e8-3041-b932-4ba0-8d5dab58b620
* Content: [AI Builder 消費レポート - AI Builder](https://docs.microsoft.com/ja-jp/ai-builder/administer-consumption-report)
* Content Source: [ai-builder-docs/administer-consumption-report.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/administer-consumption-report.md)
* Service: **aibuilder**
* GitHub Login: @CedrickBellarosa
* Microsoft Alias: **cdbellar**

**Comment by v-aangie** [comment]
@tanimani - Thanks for your feedback. We will soon look into this issue.

**Comment by CedrickBellarosa** [comment]
Approved
