### ISSUE TITLE
Screenshot needs updating

### ISSUE THREAD

**Issue by JoeFernandezMS** [MicrosoftDocs/ai-builder#60]
Screenshot for this page needs an update. 🙂 It'd be better for the screenshot to be in the AI Builder explore page in Power Automate. Thank you!

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 61b1c43a-e876-e80b-448d-be48a081d0b8
* Version Independent ID: 842cbf16-400d-04c9-09de-aa393bde0667
* Content: [Create a category classification custom model - AI Builder](https://docs.microsoft.com/en-us/ai-builder/create-text-classification-model)
* Content Source: [ai-builder-docs/create-text-classification-model.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/create-text-classification-model.md)
* Service: **aibuilder**
* GitHub Login: @v-aangie
* Microsoft Alias: **angieandrews**

**Comment by v-aangie** [comment]
This was fixed in https://github.com/MicrosoftDocs/ai-builder-pr/pull/595.
