### ISSUE TITLE
Multi Page Extraction not really working

### ISSUE THREAD

**Issue by 010101KT** [MicrosoftDocs/ai-builder#63]
I was so excited to see this article and sample flow but when I made the required changes to the flow and tested it out the multi page table extraction doesn't seem to work - some data is missed/repeated despite the tables in the Model looking perfect.

Not sure if its a bug with the flow or the OCR

#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3bd4522a-6f17-003f-7756-28bcb58ed8dd
* Version Independent ID: 60f3887a-d750-95cd-771f-e0ad0b3a9f01
* Content: [Process multipage tables in document processing (experimental) - AI Builder](https://docs.microsoft.com/en-us/ai-builder/form-processing-multipage)
* Content Source: [ai-builder-docs/form-processing-multipage.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/form-processing-multipage.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by JoeFernandezMS** [comment]
Hello @010101KT - thanks for letting us know about this. 

It might be caused due to the experimental state of this feature. We're working on improving multi page table extraction and remove experimental label in October.
