### ISSUE TITLE
flow not found

### ISSUE THREAD

**Issue by dandumit** [MicrosoftDocs/ai-builder#64]
hello
I was trying to follow the tutorial but flow for extract invoice info it's not found.
Thankyou,
daniel
[Enter feedback here]

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b9ab039-5a98-0395-eef3-2624922b81bb
* Version Independent ID: 61ea2dc3-bcb2-485e-08e1-4cdab1f272d3
* Content: [Invoice processing prebuilt AI model -  AI Builder](https://docs.microsoft.com/en-us/ai-builder/prebuilt-invoice-processing)
* Content Source: [ai-builder-docs/prebuilt-invoice-processing.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/prebuilt-invoice-processing.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by v-aangie** [comment]
@dandumit - Thanks for your feedback. I don't see where a flow for extract invoice is used in https://docs.microsoft.com/en-us/ai-builder/prebuilt-invoice-processing. Can you please be more specific with where you found this error? Thanks!

**Comment by v-aangie** [comment]
@dandumit - Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
