### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftDocs/ai-builder#65]
> Numerical prediction is when the question is answered with a number. Examples of **multiple outcome** predictions include:

Should say

> Numerical prediction is when the question is answered with a number. Examples of **numerical** predictions include:

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 04327fe0-25b9-1eca-bd13-2dd377b27cf7
* Version Independent ID: 40c93dff-6b9c-3d51-599d-d99eb0ca59f1
* Content: [Overview of the prediction model - AI Builder](https://docs.microsoft.com/en-us/ai-builder/prediction-overview)
* Content Source: [ai-builder-docs/prediction-overview.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/prediction-overview.md)
* Service: **aibuilder**
* GitHub Login: @v-aangie
* Microsoft Alias: **norliu**

**Comment by v-aangie** [comment]
@VitalyMCT - Thanks for your feedback. We have updated https://docs.microsoft.com/en-us/ai-builder/prediction-overview to fix information about numerical prediction, and the updated content will be live today. Closing this issue.

**Comment by VitalyMCT** [comment]
Thanks @v-aangie.
