### ISSUE TITLE
Typo - Automate <> Apps

### ISSUE THREAD

**Issue by MSPscripts** [MicrosoftDocs/ai-builder#67]
[In the first header](https://docs.microsoft.com/en-us/ai-builder/flow-invoice-processing) it says "For information on how to use the invoice processing prebuilt model in Power Automate, go to [Use the invoice processing prebuilt model in Power Apps](https://docs.microsoft.com/en-us/ai-builder/prebuilt-invoice-processing-powerapps)."

Should say "For information on how to use the invoice processing prebuilt model in **Power Apps**..."

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0b9ab039-5a98-0395-eef3-2624922b81bb
* Version Independent ID: 61ea2dc3-bcb2-485e-08e1-4cdab1f272d3
* Content: [Invoice processing prebuilt AI model -  AI Builder](https://docs.microsoft.com/en-us/ai-builder/prebuilt-invoice-processing)
* Content Source: [ai-builder-docs/prebuilt-invoice-processing.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/prebuilt-invoice-processing.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by v-aangie** [comment]
@MSPscripts - Thanks for your feedback. We have updated the docs to fix this issue, and the updated content will be live later today. Closing this issue.
