### ISSUE TITLE
Out of date already

### ISSUE THREAD

**Issue by iooab10** [MicrosoftDocs/ai-builder#68]
[Enter feedback here]
Article is 21 days old and already the options discussed don't exist so this article is useless.  I thought the government was blocking my access and I logged into my personal account and the options don't exist, there is no "manual extract"

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3c6628-8673-e44d-9a17-553030b6b29d
* Version Independent ID: 679b1654-ffe3-5811-6985-9333195b34d0
* Content: [Use the document processing model in Power Automate - AI Builder](https://docs.microsoft.com/en-us/ai-builder/form-processing-model-in-flow)
* Content Source: [ai-builder-docs/form-processing-model-in-flow.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/form-processing-model-in-flow.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by v-aangie** [comment]
@iooab10 - Thanks for contacting us. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
