### ISSUE TITLE
Append

### ISSUE THREAD

**Issue by iooab10** [MicrosoftDocs/ai-builder#70]
[Enter feedback here]

The picture for Append to String Variable looks like it was built in Paint.  Can you provide a screen shot of the real screen without the text hidden by whatever graphics you inserted.  Plus, explain how you get those options or did you just use paint to make this picture?

Can you explain the magic behind the append to string as I have no option for text and value and what is hidden under whateer you pasted into the picture????  Very confusing
---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 2dbf2f03-de23-1930-3121-f873904d435b
* Version Independent ID: 35979f8f-c655-c842-b0a5-a9750b48101e
* Content: [Use entity extraction model in Power Automate - AI Builder](https://docs.microsoft.com/en-us/ai-builder/prebuilt-entity-extraction-pwr-automate)
* Content Source: [ai-builder-docs/prebuilt-entity-extraction-pwr-automate.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/prebuilt-entity-extraction-pwr-automate.md)
* Service: **aibuilder**
* GitHub Login: @mfotedar
* Microsoft Alias: **mfotedar**

**Comment by v-aangie** [comment]
@iooab10 - Thanks for your feedback. We are currently reviewing this issue.

**Comment by ashbhati** [comment]
@iooab10 - Thanks for your feedback.

Step 4 in the process is to initialize a variable. We are calling the variable 'My entities' and its type as String.
![image](https://user-images.githubusercontent.com/8988531/188980740-39fd6484-fff0-45d7-92d9-27cc95883e26.png)

Step 5 is to assign the variable created in the previous step some values. for this we add action called 'Apply to each'. Which means for each entity extracted by the AI builder entity extraction model repeat the enclosed steps. 

Then for the enclosed steps we add the action called 'Append to string variable', which adds a new entity to the already existing content of the 'My entities' variable. In the end the variable will be a long string with each individual and its value concatenated as a string. 
![image](https://user-images.githubusercontent.com/8988531/188982143-36f371e9-c9c4-461d-aa66-d360cfa9ac11.png)

In the last step we are composing an email and sending the content of the 'My entities' variable in the body of an email.

I hope this explains the flow. Feel free to ask clarifying questions.
