### ISSUE TITLE
Formula Error

### ISSUE THREAD

**Issue by KylieKiser** [MicrosoftDocs/ai-builder#71]
'Car Damage Classifier'.Predict(AddMediaButton.Media).Prediction
is no longer the correct formula.

This should be 
'Car Damage Classifier'.Predict(AddMediaButton.Media).TopClass.Name

Prediction is not recognized

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cc82aee7-7245-42a3-41e9-a8d2aa3eed19
* Version Independent ID: cc82aee7-7245-42a3-41e9-a8d2aa3eed19
* Content: [Use image classification model by Lobe in Power Apps - AI Builder](https://docs.microsoft.com/en-us/ai-builder/image-classification-component-in-powerapps)
* Content Source: [ai-builder-docs/image-classification-component-in-powerapps.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/image-classification-component-in-powerapps.md)
* Service: **aibuilder**
* GitHub Login: @v-aangie
* Microsoft Alias: **angieandrews**

**Comment by v-aangie** [comment]
@arijitba - Please confirm that this correction is needed. We should either update the animation or replace with instructions. Please let me know how to proceed. Thanks!

**Comment by v-aangie** [comment]
@KylieKiser - Thanks for your feedback. We will soon look into this issue.

**Comment by v-aangie** [comment]
Sent updated email to @arijitba 9/30/2022.

**Comment by v-aangie** [comment]
@KylieKiser - Thank you raising this issue on https://learn.microsoft.com/en-us/ai-builder/image-classification-component-in-powerapps. Closing this issue, as Lobe is now deprecated. The documentation will be updated with details soon.
