### ISSUE TITLE
Pointing out typo: "開始l" -> "開始"

### ISSUE THREAD

**Issue by Toxumuharu** [MicrosoftDocs/ai-builder#72]
Hi team, just I would point out for one typo.

The letter "l" in the attention area after "開始" should be removed. - https://docs.microsoft.com/ja-jp/ai-builder/administer-licensing#trial-licenses
>  注意
\
キャパシティ アドオンの購入や他の製品によって、テナントに既に AI Builder のクレジットがある場合は、AI Builder のトライアルを**開始l** することはできません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8a416cb4-e549-8257-4630-7979f812c3d7
* Version Independent ID: 4e0e4713-135d-0f82-75ac-836a716e12f3
* Content: [AI Builder のライセンス - AI Builder](https://docs.microsoft.com/ja-jp/ai-builder/administer-licensing)
* Content Source: [ai-builder-docs/administer-licensing.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/administer-licensing.md)
* Service: **aibuilder**
* GitHub Login: @Phil-cmd
* Microsoft Alias: **plarrue**

**Comment by v-aangie** [comment]
@Toxumuharu - Thanks for your feedback. Our localization team will soon address this issue.

**Comment by Bernadette2022** [comment]
The feedback has been implemented in the md file.  This is now fixed.  Thanks for sharing the feedback.

**Comment by Bernadette2022** [comment]
Copying fix here:
 注意

キャパシティ アドオンの購入や他の製品によって、テナントに既に AI Builder のクレジットがある場合は、AI Builder のトライアルを開始 することはできません。

**Comment by v-aangie** [comment]
Our translator has fixed this issue and the update is now reflected here: https://docs.microsoft.com/ja-jp/ai-builder/administer-licensing. Closing the issue.
