### ISSUE TITLE
What is the source of the US Government roadmap?

### ISSUE THREAD

**Issue by denpsch** [MicrosoftDocs/ai-builder#74]
[Enter feedback here]
Under Custom Models and Prebuilt Models it is not clear what date(s) these were released to GA and the associated product roadmap. When I lookup the roadmap at this link (https://dynamics.microsoft.com/en-us/roadmap/overview/) it does not distinguish between the regions.  

Thanks! feel free to reach me on teams or here for more details.
dschnell

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 665785c6-bcb9-49a2-7cf7-bc0bfbbde698
* Version Independent ID: 7d4bb419-100c-430f-9ec1-396f7c3c51a7
* Content: [Feature availability by region or US Government environment - AI Builder](https://learn.microsoft.com/en-us/ai-builder/availability-region?source=docs)
* Content Source: [ai-builder-docs/availability-region.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/availability-region.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by v-aangie** [comment]
@denpsch - Thank you for raising this issue. Sorry for the delay. For release dates, we typically provide information here: [Overview of AI Builder 2022 release wave 2 | Microsoft Learn](https://learn.microsoft.com/en-us/power-platform-release-plan/2022wave2/ai-builder/). Please let me know if you're looking for specific feature GA data and I'll try to locate it. Thanks.
