### ISSUE TITLE
ca virro

### ISSUE THREAD

**Issue by AYOUBHSN14** [MicrosoftDocs/ai-builder#75]
[اكتب ملاحظاتك هنا]

---
#### تفاصيل المستند

⚠ *تجنب تحرير هذا القسم. مطلوب لـ learn.microsoft.com ➟ ربط مشكلة GitHub.*

* ID: 0b9ab039-5a98-0395-eef3-2624922b81bb
* Version Independent ID: 61ea2dc3-bcb2-485e-08e1-4cdab1f272d3
* Content: [Invoice processing prebuilt AI model -  AI Builder](https://learn.microsoft.com/ar-sa/ai-builder/prebuilt-invoice-processing)
* Content Source: [ai-builder-docs/prebuilt-invoice-processing.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/prebuilt-invoice-processing.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by Bernadette2022** [comment]
Could you please clarify your feedback or what issue we need to address?

**Comment by Bernadette2022** [comment]
@AYOUBHSN14 could you clarify the issue .  We are unclear what issue is being reported in this topic

**Comment by v-aangie** [comment]
Per Bernadette 1/31/2023 Teams chat, this issue is invalid. Closing the issue.

**Comment by v-aangie** [comment]
@AYOUBHSN14 - Thanks for contacting us about https://learn.microsoft.com/ar-sa/ai-builder/prebuilt-invoice-processing. As we haven’t heard back from you, I am closing this issue. If you need further help, please reopen the issue or open a new issue.
