### ISSUE TITLE
Document processing

### ISSUE THREAD

**Issue by J227668** [MicrosoftDocs/ai-builder#77]
Can you please confirm if custom models - Document processing (for unstructured documents) is available in GCCH? Someone referenced it might be available. 

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 665785c6-bcb9-49a2-7cf7-bc0bfbbde698
* Version Independent ID: 7d4bb419-100c-430f-9ec1-396f7c3c51a7
* Content: [Feature availability by region or US Government environment - AI Builder](https://learn.microsoft.com/en-us/ai-builder/availability-region#custom-models-1)
* Content Source: [ai-builder-docs/availability-region.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/availability-region.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by JoeFernandezMS** [comment]
Hello! Yes, I can confirm that Document processing (for unstructured documents) is available in GCC and GCCH since December 6th. We'll update the documentation shortly. Thank you for asking.
