### ISSUE TITLE
Add Custom Fields

### ISSUE THREAD

**Issue by LeanLL** [MicrosoftDocs/ai-builder#8]
It's possible to add custom Fields? I didn't find a feature to do this.

---
#### Detalhes do documento

⚠ *Não edite esta seção. É necessário para a vinculação do problema do docs.microsoft.com ➟ GitHub.*

* ID: 6626b8f6-7e78-8c29-781f-c8afc2d44a03
* Version Independent ID: f66cc87b-ea72-9b25-d85d-729c016b5c4a
* Content: [Create a form processing model -  AI Builder](https://docs.microsoft.com/pt-br/ai-builder/create-form-processing-model#feedback)
* Content Source: [ai-builder-docs/create-form-processing-model.md](https://github.com/MicrosoftDocs/ai-builder/blob/master/ai-builder-docs/create-form-processing-model.md)
* Service: **powerapps**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by JoeFernandezMS** [comment]
Hi @LeanLL. Adding custom fields is not supported today, but stay tuned for upcoming updated :)
