### ISSUE TITLE
Bring your own AI model link lands on Learn home page

### ISSUE THREAD

**Issue by anttipajunen** [MicrosoftDocs/ai-builder#81]
Choosing "Bring your own AI model" leads to https://learn.microsoft.com/en-us/

This feels unintentional.

See image below:
![image](https://user-images.githubusercontent.com/64043240/221121921-399a7c69-af41-4f41-9fc5-0722d2803713.png)

**Comment by chosen-one1** [comment]
What be the next steps I’m interested in getting involved and helping develop the community for the better!
Thomas N Sanders

**Comment by KumarVivek** [comment]
@anttipajunen Thanks for the feedback. The **Bring your own model** was an orphan entry. This is the topic that it was supposed to point to: https://learn.microsoft.com/en-us/ai-builder/byo-model

We have removed the entry from TOC. Closing the issue.
