### ISSUE TITLE
Request to add more details for field coordinates, polygons, and bounding boxes

### ISSUE THREAD

**Issue by Blake-renewables** [MicrosoftDocs/ai-builder#82]
Hello, I am trying to utilize the field coordinates, polygons, and bounding box output parameters from the Power Automate AI builder document processing model. I'd like to understand how the extracted variable's Location JSON output can be used to find the extracted variable's location in a .pdf editor like Bluebeam. With no success, I've tried scaling the coordinates from the JSON output in a python script to make a .pdf comment/markup in the editor.  Please add more information about what the extracted variable's Location JSON data represents in terms of the actual location in a .pdf editor.

Thank you!!

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3c6628-8673-e44d-9a17-553030b6b29d
* Version Independent ID: 679b1654-ffe3-5811-6985-9333195b34d0
* Content: [Use the document processing model in Power Automate - AI Builder](https://learn.microsoft.com/en-us/ai-builder/form-processing-model-in-flow)
* Content Source: [ai-builder-docs/form-processing-model-in-flow.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/form-processing-model-in-flow.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by v-aangie** [comment]
@Blake-renewables - Thanks for your feedback. We will soon look into this issue.
