### ISSUE TITLE
Clarification on how the 5,000 credit are applied

### ISSUE THREAD

**Issue by sboulanger86** [MicrosoftDocs/ai-builder#83]
It's not clear if the 5,000 credit included in the per user plan are usable by the organization or only by the user. I receive questions from customers asking if it's applied to the tenant level or user level. I validated with Cedrick that it's at the tenant level and will suggest we update the documentation to reflect this.

**Comment by v-aangie** [comment]
@sboulanger86 - Thanks for contacting us. As this issue concerns an understanding/clarification of licensing guidance, it isn't something that we should add to the documentation. Please see https://go.microsoft.com/fwlink/?linkid=2085130, page 9, "Power Automate per user with attended RPA plan", Notes section. It says, "AI Builder service credit capacity is pooled at the tenant level".

For licensing issues, please contact Sales at the bottom of this pricing page: https://powerautomate.microsoft.com/en-us/pricing/. Closing this issue.

cc: @CedrickBellarosa
