### ISSUE TITLE
Preview form closed for submissions

### ISSUE THREAD

**Issue by kasavin** [MicrosoftDocs/ai-builder#85]
The [Limited preview request](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbR2LogRPRiTJDo1Rd8KnmcFRUMzlLTDZVQlJKSzNIWkVCMzE0VDFYVzk2QS4u) form is no longer accepting submissions. Are there plans to reopen the preview? Otherwise I would remove the form.

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out, the form is removed.
