### ISSUE TITLE
Instructions and Images are incorrect

### ISSUE THREAD

**Issue by ML1961** [MicrosoftDocs/ai-builder#87]
I have saved (and published) an invoice processing model in AI Builder/Models.
I am now trying to create a flow that is triggered when a file is added to a Sharepoint document folder.

Step 6 says : Select +New step > AI Builder, and then select Extract information **from forms** in the list of actions.
I do not get a matching result from my search.
![image](https://github.com/MicrosoftDocs/ai-builder/assets/112146997/beab87d6-b557-4530-b573-7d944dea3ed2)

And if I choose 'Extract Information from Invoices' - I am unable to select a model.
![image](https://github.com/MicrosoftDocs/ai-builder/assets/112146997/dda07dad-63d2-4a2d-8760-2f315fca0f21)

So how do I add an existing model to new flow.

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 0a3c6628-8673-e44d-9a17-553030b6b29d
* Version Independent ID: 679b1654-ffe3-5811-6985-9333195b34d0
* Content: [Use the document processing model in Power Automate](https://learn.microsoft.com/en-us/ai-builder/form-processing-model-in-flow)
* Content Source: [ai-builder-docs/form-processing-model-in-flow.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/form-processing-model-in-flow.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by v-aangie** [comment]
@ML1961 - Thanks for your feedback. We have updated the docs to fix information about the forms action, and the updated content will be live within an hour. The Extract information from forms action has been renamed Extract information from documents. (see screenshot below). Closing this issue. If this action doesn't resolve your issue, please reopen this issue or create a new one. Thanks!

![image](https://github.com/MicrosoftDocs/ai-builder/assets/68758324/9ec458cf-31ad-4905-821d-c92777fd8346)

**Comment by v-aangie** [comment]
Updated docs in https://github.com/MicrosoftDocs/ai-builder-pr/pull/752,
