### ISSUE TITLE
error using dynamics operation request to API

### ISSUE THREAD

**Issue by makdaddy8888** [MicrosoftDocs/ai-builder#91]
[Enter feedback here]

Flow save failed with code 'DynamicOperationRequestClientFailure' and message 'The dynamic operation request to API 'excelonlinebusiness' operation 'GetTable' failed with status code '429'. This may indicate invalid input parameters. Error response: { "status": 429, "message": "Too many requests to Graph API. Please try again later.\r\nclientRequestId: b5992653-1722-4521-909e-6f37310748aa\r\nserviceRequestId: 9598c447-2f12-4d8b-bed5-e930963eb9a4", "error": { "message": "Too many requests to Graph API. Please try again later." }, "source": "excelonline-eus2.azconn-eus2-003.p.azurewebsites.net" }'.
---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 3ad6b781-6546-f571-dbb0-c93aa21ce29a
* Version Independent ID: 1db2927e-c39e-9813-9ce8-d454c7e91640
* Content: [Use the receipt processing prebuilt model in Power Automate - AI Builder](https://learn.microsoft.com/en-us/ai-builder/flow-receipt-processing)
* Content Source: [ai-builder-docs/flow-receipt-processing.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/flow-receipt-processing.md)
* Service: **aibuilder**
* GitHub Login: @v-aangie
* Microsoft Alias: **angieandrews**

**Comment by tapanm-MSFT** [comment]
Thank you for reaching out. Please contact support to get help with the issue investigation and resolution. More information: [Get help + support](https://learn.microsoft.com/power-platform/admin/get-help-support)
