### ISSUE TITLE
Additional clarification questions

### ISSUE THREAD

**Issue by MichaelWeberMSFT** [MicrosoftDocs/ai-builder#99]
Hi,

can you please add following question to this great FAQ page. Unfortunately we were not able to find this information in the licensing guide or in the calculator:

1.	If a document was 10 pages and only one take information from on page, am I billed for the one or 10 pages?
2.	When your train the model, how do you know which capacity the model is using?

Thank you so much,
Michael

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: 273b2de4-8f7e-71fd-0643-da698c435dca
* Version Independent ID: 70876778-4884-1703-0236-fd4a04597c91
* Content: [Frequently asked questions (FAQ) for document processing - AI Builder](https://learn.microsoft.com/en-gb/ai-builder/form-processing-faq)
* Content Source: [ai-builder-docs/form-processing-faq.md](https://github.com/MicrosoftDocs/ai-builder/blob/main/ai-builder-docs/form-processing-faq.md)
* Service: **aibuilder**
* GitHub Login: @JoeFernandezMS
* Microsoft Alias: **jofernan**

**Comment by v-aangie** [comment]
@MichaelWeberMSFT - Thanks for your feedback. We are looking into this issue.

**Comment by Antrodfr** [comment]
Hi, thanks for the feedback! 

The information about cost per page is indicated at the bottom of the page: https://learn.microsoft.com/ai-builder/form-processing-faq#how-much-does-ai-builder-document-processing-cost

"Every page you process with document processing will consume AI Builder credits"

We can perhaps add to this sentence "even if the page doesn't contain any data to extract".

**Comment by v-aangie** [comment]
@MichaelWeberMSFT - Thanks for your feedback. We have updated the docs to fix information about the billing issue, and the updated content is live. Closing this issue.

**Comment by MichaelWeberMSFT** [comment]
Thank you!
